### ISSUE TITLE
Update for turnip 4.4

### ISSUE THREAD

**Issue by leoc** [aramvisser/turnip_documentation_formatter#2]
Hi Aram!

I just releases 4.4 of turnip including your notification changes. 

I just wanted to create a PR bumping the dependency to '>= 4.4', but I think there are more changes necessary. 
Now we can avoid patching turnip itself and just write the formatter based on these notifications, right? :smile: 

What may be the reason for not using your documentation formatter as default for turnip?

I see you are monkey patching turnip and the rspec core documentation formatter. Maybe we can inherit from the documentation formatter and provide a specific `turnip_documentation` or `documentation_with_turnip` formatter, so that we do not cause unintended issues for the users?

Maybe we can add some docs to the README of turnip?

In any case thanks a lot!

Cheers to Cambodia!

**Comment by aramvisser** [comment]
Hi Arthur,

Great that you're releasing a new Turbip version with my patches! I'll release a new version soon that depends on Turnip 4.4. Aside from the dependency, the only change will be to remove the Turnip patches that have now been merged.

The default documentation formatter is being monkey patched so that user's don't have to specify a different formatter when they want to see turnip output. They can just specify the default documentation formatter that they're already familiar with. Any non turnip examples will use the original formatter. So you can use the same formatter for both Turnip and regular RSpec examples at the same time.

I think it won't be any problem if this became the default documentation formatter for Turnip. The only problem might be if someone depends on the exact format for the current documentation format the way it is now, but I can't see a good reason why someone would do that.

**Comment by aramvisser** [comment]
Hey Arthur,

I just released version 0.1, which depends on Turnip 4.4 and removes the turnip patches. So this formatter can now be considered stable.
